title: Meagan Fairfield-Peak # your name (or website title) here
logo: "/images/Fairfield-Peak_Meagan (2).jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student at University of Maryland, Baltimore County 
  <br><br>
  Interest: Landscape Geography, Landscape Management, GIS, Remote Sensing  
  <br><br>
  <a href="https://www.linkedin.com/in/meaganfairfield/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
